apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: flask
        image: inemyrovsk/helm-demo:v11
        imagePullPolicy: IfNotPresent
        env:
          - name: DEPLOY_ENV
            value: "TEST"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "5000"
        ports:
        - containerPort: 5000
      nodeSelector:
        environment: test
