apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
data:
  logstash.yml: |
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
          hosts => ["https://elasticsearch-master:9200"]
          index => "logstash-%{[kubernetes][namespace]}-%{+YYYY.MM.dd}"
          user => "elastic"
          password => "kuydWOlFxDdCLi1J"
          cacert => '/etc/logstash/certificates/ca.crt'
      }
    }